### ISSUE TITLE
pcap file ?

### ISSUE THREAD

**Issue by xmaxmex** [jrbenito/isec-wireshark#1]
Hi JrBenito,

You have a pcap file for this session ? We trying develop one IP receptor, but this protoclo is closed :(

Can help ?

Thanks in advance.

**Comment by jrbenito** [comment]
Hi @xmaxmex,

I need to check if I still have pcap and if the pcap does not contain any secure information because passwords are transmitted in plain text :(

I am out of home until wed, so I will only be able to check on next wed. In the meantime, Intelbras gave me protocol specs with no fuss, I only had to commit to their NDA and received PDFs as necessary. This plugin was developed based on their PDF just to make debug easy. 

BR,
Benito

**Comment by jrbenito** [comment]
@xmaxmex ,

I am sorry but I don´t have pcap files anymore and I am unable to get new ones right now because I have no access to the panel.

BR,
Benito
